In [1]:
import numpy as np

#### Arithmetic Operators

In [6]:
a = np.array( [[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [2]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [3]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
a * a

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [5]:
a ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [6]:
a + a

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [7]:
1/a

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

#### Matrix operations

In [8]:
A = np.array( [[1,3],[0,1]] )
B = np.array( [[2,2],[3,4]] )

In [9]:
A*B                # 直接相乘是对每个元素相乘 elementwise product

array([[2, 6],
       [0, 4]])

In [10]:
A.dot(B)           # .dot()是矩阵相乘 matrix product

array([[11, 14],
       [ 3,  4]])

In [11]:
np.dot(A, B)

array([[11, 14],
       [ 3,  4]])

In [12]:
np.add(A, B)

array([[3, 5],
       [3, 5]])

#### Other Operations

In [16]:
# np.random.random 是在半开放区间[0.0, 1.0) 之间生成随机数字
#Return random floats in the half-open interval [0.0, 1.0).

a = np.random.random([3,3]) 
a

array([[ 0.95894783,  0.94959197,  0.3586988 ],
       [ 0.47279963,  0.50952665,  0.94852705],
       [ 0.37048593,  0.35073787,  0.05880844]])

In [15]:
np.random.randn(3,3)

array([[ 0.37121831,  0.63210725, -1.99195465],
       [-1.3564321 ,  0.73916868, -0.69646906],
       [ 0.09232577,  1.57556329, -0.19773931]])

In [17]:
a.sum()

4.978124169044631

In [15]:
a.min()

0.24797052126014996

In [16]:
a.max()

0.98286015105901836

In [18]:
b = np.arange(24).reshape(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [2]:
# 关于 axis： axis=0 是沿着每一行每一行操作  axis=1 是沿着每一列每一列操作

In [18]:
b.sum(axis=0) # sum of each column

array([60, 66, 72, 78])

In [19]:
b.sum(axis=1) # sum of each row

array([ 6, 22, 38, 54, 70, 86])

In [20]:
b.min(axis=1) # min of each row

array([ 0,  4,  8, 12, 16, 20])

In [21]:
b.cumsum(axis=1) # 累计相加 cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54],
       [16, 33, 51, 70],
       [20, 41, 63, 86]], dtype=int32)