In [1]:
# 这一小节我们来讲 np array 的选取，我们先来看看一维array的选取，然后我们进行二维以及多维 array的选取

#### One-dimensional arrays.

In [1]:
import numpy as np

In [2]:
a = np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [2]:
# 我们从0开始数 0,1,2,3,4,5 第5个位置 对应的元素是 25

In [4]:
a[2]

4

In [3]:
# [2:6] 的意思是 选取位置是 2，3，4, 5 这四个元素

In [4]:
a[2:6] 

array([ 4,  9, 16, 25])

In [5]:
a[0:3] = 100
a

array([100, 100, 100,   9,  16,  25,  36,  49,  64,  81], dtype=int32)

In [6]:
a_slice = a[0:5]
a_slice

array([100, 100, 100,   9,  16], dtype=int32)

In [9]:
# 注意： 当我们选取部分 np array 的时候，我们创建了一个view。
# 换句话说，我们没有copy以前的值，而是直接改了原来的 array 

a_slice[0] = 233
print(a_slice)
print(a)

[233 100 100   9  16]
[233 100 100   9  16  25  36  49  64  81]


In [9]:
# 如果不想对原来的 array 进行修改，我们可以把选取的部分 copy 出来

a_slice_2 = a[0:5].copy()
a_slice_2

array([200, 100, 100,   9,  16])

In [10]:
a_slice_2[0] = 500
a

array([200, 100, 100,   9,  16,  25,  36,  49,  64,  81])

## Multidimensional arrays.

In [10]:
def f(x,y):
    return 4 * x + y
b = np.fromfunction(f,(3,2),dtype=int)
b

# derive from locations of the matrix
#[[00],[01],[10],[11],[20],[21]]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [14]:
b[1]

array([4, 5])

In [15]:
b[1][0]

4

In [15]:
b[1,0]

4

In [16]:
b[:, 1]

array([1, 5, 9])

In [17]:
c = np.zeros ([5,5])
c

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [8]:
column_length = c.shape[1]
column_length

5

In [10]:
for i in range(column_length):
    c[i] = i
    print(c[i])

[ 0.  0.  0.  0.  0.]
[ 1.  1.  1.  1.  1.]
[ 2.  2.  2.  2.  2.]
[ 3.  3.  3.  3.  3.]
[ 4.  4.  4.  4.  4.]


In [21]:
for i in range(5):
    c[i]=i+1
    

In [19]:
c

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.]])

#### Boolean Indexing

In [22]:
week_days=np.array(['Monday','Tuesday','Wednesday','Thursday','Friday'])

In [23]:
work_time=np.round(np.random.randn(5,5)+8.0, 2)

In [24]:
work_time

array([[ 7.82,  8.48,  8.03,  7.97,  7.31],
       [ 5.45,  9.18,  8.62,  8.25,  7.85],
       [ 7.8 ,  9.02,  6.89,  7.33,  8.6 ],
       [ 9.54,  9.27,  7.19,  8.25,  7.11],
       [ 7.47,  7.41,  8.45,  8.7 ,  8.3 ]])

In [32]:
week_days == 'Tuesday'

array([False,  True, False, False, False], dtype=bool)

In [33]:
work_time[week_days == 'Tuesday']

array([[ 8.03,  7.74,  9.46,  7.31,  9.09]])