In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.exp(a)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [7]:
np.sqrt(a)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [9]:
b = np.random.randn(10)
b

array([ 0.5950729 ,  0.34703129,  0.04497741,  0.69667061,  0.15233449,
        0.77032584, -0.17686948, -1.70686557, -0.34629533, -0.61446124])

In [3]:
c = np.random.randn(10).reshape(2,5)
c

array([[ 0.23333335, -0.25237544, -0.73610691, -0.07272651,  0.85959587],
       [-0.9878741 ,  0.3863078 ,  0.12858347,  0.11681238, -0.34344447]])

In [11]:
# Binary Functions
np.add(b,c)

array([-0.44751905,  0.02907221,  2.2269195 , -1.54937333,  1.60076085,
        2.03151324, -1.4535573 , -1.37325156, -1.45352241, -2.76061538])