In [1]:
import numpy as np

## Saving array in binary format (.npy)

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
np.save('array_a',a)

In [4]:
np.load('array_a.npy')

array([1, 2, 3, 4, 5])

## Saving multiple arrays into a zip file

In [5]:
b = np.array([[1,2,3],[4,5,6]])

In [6]:
np.savez('two_arrays.npz',x=b,y=b.T)

In [7]:
np.load('two_arrays.npz')['x']

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.load('two_arrays.npz')['y']

array([[1, 4],
       [2, 5],
       [3, 6]])

## Saving and loading into text files

In [9]:
np.savetxt('array_text.txt',b,delimiter=',')

In [10]:
np.loadtxt('array_text.txt',delimiter=',')

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])