## numpy

In [1]:
import numpy as np
t=(1,2,3)

In [13]:
a=np.array(t,dtype='int32')
a

array([1, 2, 3])

In [12]:
list1=[1,2,3]
a=np.array(list1,dtype='double')
a

array([ 1.,  2.,  3.])

In [19]:
list2=[4,5,6]
b=np.array([list1,list2])
b
# np.isnan(list1)


array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
c=np.array([[1,2],[3,4]],dtype=complex)
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [23]:
np.array([[1,2],[3,4]],dtype=complex)

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [22]:
np.zeros([2,2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [24]:
np.empty([2,2])

array([[ 0.,  0.],
       [ 0.,  0.]])

In [29]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [34]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [35]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [36]:
np.save('array_a',a)
np.load('array_a.npy')

array([1, 2, 3])

In [41]:
bb=np.array([[1,2,3],[4,5,6]])
np.savez('two_arrays.npz',x=bb,y=bb.T)

In [ ]:
np.save

In [47]:
x=np.array([[1,2],[2,4]])
y=np.array([[1,3],[1,4]])
x

array([[1, 2],
       [2, 4]])

In [56]:
np.dot(x,y)

array([[ 3, 11],
       [ 6, 22]])

In [58]:
x.sum()

9

In [59]:
x.min()

1

In [60]:
x.max()

4

In [61]:
x.sum(axis=0)

array([3, 6])

In [62]:
x.sum(axis=1)

array([3, 6])

In [63]:
x.min(axis=1)

array([1, 2])

In [66]:
x.max(axis=1)

array([2, 4])

In [68]:
b=np.arange(24).reshape(4,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [69]:
b.cumsum(axis=1)

array([[  0,   1,   3,   6,  10,  15],
       [  6,  13,  21,  30,  40,  51],
       [ 12,  25,  39,  54,  70,  87],
       [ 18,  37,  57,  78, 100, 123]], dtype=int32)

In [70]:
b.cumsum(axis=0)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14, 16],
       [18, 21, 24, 27, 30, 33],
       [36, 40, 44, 48, 52, 56]], dtype=int32)

In [49]:
np.random.random([3,3])

array([[ 0.0739174 ,  0.22852017,  0.90212646],
       [ 0.1056931 ,  0.69750544,  0.95595087],
       [ 0.11536507,  0.57217363,  0.36780122]])

In [51]:
np.random.randn(3,3)

array([[ 0.7996405 , -0.32953275, -0.92973546],
       [ 0.03751108, -0.03133606, -1.14480427],
       [-0.89475638, -0.19402614, -1.7206289 ]])

In [55]:
np.random.randint(300)

293

In [72]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
a[2]

2

In [74]:
a[2:6]

array([2, 3, 4, 5])

In [79]:
a[0:3]=100
a

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [76]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [82]:
a_slice=a[0:5].copy()
a_slice

array([100, 100, 100,   3,   4])

In [83]:
a_slice[0]=300
a_slice

array([300, 100, 100,   3,   4])

In [84]:
a

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [93]:
def f(x,y):
    return x+y
b = f(1,2)
b

3

In [94]:
b = np.fromfunction(f,(3,2),dtype=int)
b

array([[0, 1],
       [1, 2],
       [2, 3]])

In [96]:
b[0][1]

1

In [97]:
b[0,1]

1

In [98]:
b[:,1]

array([1, 2, 3])

In [99]:
c=np.zeros([5,5])
c

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [102]:
range(5)
range(0,5)

range(0, 5)

## pandas

In [103]:
import pandas as pd;
import numpy as np;



In [106]:
df = pd.read_csv('C:\\Users\\Roger\\Desktop\\train.csv')
df.shape

(891, 12)

In [107]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [108]:
df.tail(3)

PassengerId  Survived  Pclass                                      Name  \
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [109]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [110]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [119]:
df['Name'].head(5)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

## matplotlix

In [132]:
import matplotlib as plot

weather_df = pd.read_csv('C:\\Users\\Roger\\Desktop\\weather_2012.csv')
weather_df.head(5)

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0  2012-01-01 00:00:00      -1.8                -3.9           86   
1  2012-01-01 01:00:00      -1.8                -3.7           87   
2  2012-01-01 02:00:00      -1.8                -3.4           89   
3  2012-01-01 03:00:00      -1.5                -3.2           88   
4  2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                4              8.0           101.24                   Fog  
1                4              8.0           101.24                   Fog  
2                7              4.0           101.26  Freezing Drizzle,Fog  
3                6              4.0           101.27  Freezing Drizzle,Fog  
4                7              4.8           101.23                   Fog

In [135]:
weather_df.shape

(8784, 8)

In [133]:
weather_df['Tem(C)'].plot(15,6)

KeyError: 'Tem(C)'